version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql
  micro:
    image: davidbzhao/judging
    container_name: judging_microservices
    volumes:
      - ./app:/app
    ports:
      - "5082:8000"
    depends_on:
      - db
    command: bash -c "npm install;
      while !</dev/tcp/db/5432; do sleep 1; done;
      python /app/judging/manage.py migrate &&
      python /app/judging/manage.py collectstatic --noinput;
      mod_wsgi-express start-server
        --working-directory /app/judging
        --url-alias /static /app/judging/staticfiles
        --reload-on-changes
        /app/judging/judging/wsgi.py"
  exp:
    image: davidbzhao/judging
    container_name: judging_experiences
    volumes:
      - ./app:/app
    links:
      - micro:micro
    ports:
      - "5081:8000"
    depends_on:
      - micro
    command: bash -c "npm install;
      python /app/exp/manage.py migrate;
      mod_wsgi-express start-server
        --working-directory /app/exp
        --reload-on-changes
        /app/exp/exp/wsgi.py"
  web:
    image: davidbzhao/judging
    container_name: judging_frontend
    volumes:
      - ./app:/app
    links:
      - exp:exp
    ports:
      - "5080:8000"
    depends_on:
      - exp
    command: bash -c "npm install;
      python /app/web/manage.py migrate &&
      python /app/web/manage.py collectstatic --noinput;
      mod_wsgi-express start-server
        --working-directory /app/web
        --url-alias /static /app/web/staticfiles
        --reload-on-changes
        /app/web/web/wsgi.py"